

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


-- CREATE EXTENSION IF NOT EXISTS "pgsodium" WITH SCHEMA "pgsodium";
-- See https://github.com/supabase/cli/issues/3358#issuecomment-2755803583






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgjwt" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE OR REPLACE FUNCTION "public"."get_challenges_completed"() RETURNS TABLE("player" "uuid", "total_challenges" bigint, "total_seconds" bigint)
    LANGUAGE "plpgsql"
    AS $$BEGIN
    RETURN QUERY
    SELECT
        cc.player,
        COUNT(cc.challenge)::BIGINT AS total_challenges, -- Cast COUNT to BIGINT
        SUM(CAST(EXTRACT(EPOCH FROM (cc.created_at - c.started_at)) AS BIGINT))::BIGINT AS total_seconds -- Double cast to ensure BIGINT
    FROM
        public.challenges_completed cc
    INNER JOIN
        public.challenges c
        ON cc.challenge = c.id
    WHERE
        c.started_at IS NOT NULL -- Filter out rows with NULL started_at
    GROUP BY
        cc.player
    ORDER BY
        COUNT(cc.challenge)::BIGINT DESC, -- Ensure COUNT is cast for ORDER BY
        SUM(CAST(EXTRACT(EPOCH FROM (cc.created_at - c.started_at)) AS BIGINT))::BIGINT ASC; -- Cast SUM for ORDER BY
END;$$;


ALTER FUNCTION "public"."get_challenges_completed"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_daily_ranking"() RETURNS TABLE("player" "uuid", "seconds" bigint)
    LANGUAGE "plpgsql"
    AS $$
begin
  return query
  select 
    cc.player,
    extract(epoch from (cc.created_at - c.started_at))::bigint as seconds
  from 
    public.challenges c
  join 
    public.challenges_completed cc
    on c.id = cc.challenge
  where 
    c.started_at is not null
  and 
    c.started_at = (
      select max(started_at)
      from public.challenges
      where started_at is not null
    )
  order by 
    seconds asc;
end;
$$;


ALTER FUNCTION "public"."get_daily_ranking"() OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."attempts" (
    "player" "uuid" NOT NULL,
    "challenge" bigint NOT NULL,
    "attempts" "jsonb" DEFAULT '[]'::"jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL
);


ALTER TABLE "public"."attempts" OWNER TO "postgres";


COMMENT ON TABLE "public"."attempts" IS 'Attempts of each player per challenge';



CREATE TABLE IF NOT EXISTS "public"."challenges" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "word" "text" NOT NULL,
    "description" "text",
    "started_at" timestamp with time zone,
    CONSTRAINT "word_length_check" CHECK ((("char_length"("word") >= 5) AND ("char_length"("word") <= 6)))
);


ALTER TABLE "public"."challenges" OWNER TO "postgres";


COMMENT ON TABLE "public"."challenges" IS 'Daily challenges';



CREATE TABLE IF NOT EXISTS "public"."challenges_completed" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "challenge" bigint NOT NULL,
    "player" "uuid" NOT NULL
);


ALTER TABLE "public"."challenges_completed" OWNER TO "postgres";


COMMENT ON TABLE "public"."challenges_completed" IS 'Challenges completed per player';



ALTER TABLE "public"."challenges" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."challenges_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."subscriptions" (
    "endpoint" "text" NOT NULL,
    "keys" "jsonb",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "expirationTime" "text",
    "player" "uuid" NOT NULL
);


ALTER TABLE "public"."subscriptions" OWNER TO "postgres";


COMMENT ON TABLE "public"."subscriptions" IS 'Web push notification subscriptions';



ALTER TABLE ONLY "public"."attempts"
    ADD CONSTRAINT "attempts_pkey" PRIMARY KEY ("challenge", "player");



ALTER TABLE ONLY "public"."challenges_completed"
    ADD CONSTRAINT "challenges_completed_pkey" PRIMARY KEY ("challenge", "player");



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "challenges_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_pkey" PRIMARY KEY ("endpoint", "player");



ALTER TABLE ONLY "public"."challenges"
    ADD CONSTRAINT "unique_word" UNIQUE ("word");



ALTER TABLE ONLY "public"."attempts"
    ADD CONSTRAINT "attempts_challenge_fkey" FOREIGN KEY ("challenge") REFERENCES "public"."challenges"("id");



ALTER TABLE ONLY "public"."attempts"
    ADD CONSTRAINT "attempts_player_fkey" FOREIGN KEY ("player") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."challenges_completed"
    ADD CONSTRAINT "challenges_completed_challenge_fkey" FOREIGN KEY ("challenge") REFERENCES "public"."challenges"("id");



ALTER TABLE ONLY "public"."challenges_completed"
    ADD CONSTRAINT "challenges_completed_player_fkey" FOREIGN KEY ("player") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."subscriptions"
    ADD CONSTRAINT "subscriptions_player_fkey" FOREIGN KEY ("player") REFERENCES "auth"."users"("id");



CREATE POLICY "Allow authenticated users select" ON "public"."challenges" FOR SELECT TO "authenticated" USING (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Allow authenticated users select their subscriptions" ON "public"."subscriptions" FOR SELECT USING (("player" = "auth"."uid"()));



CREATE POLICY "Allow authenticated users subscribe to notifications" ON "public"."subscriptions" FOR INSERT TO "authenticated" WITH CHECK (("auth"."uid"() IS NOT NULL));



CREATE POLICY "Allow authenticated users to insert their own attempts" ON "public"."attempts" FOR INSERT WITH CHECK (("player" = "auth"."uid"()));



CREATE POLICY "Allow authenticated users to read their completed challenges" ON "public"."challenges_completed" FOR SELECT TO "authenticated" USING (("player" = "auth"."uid"()));



CREATE POLICY "Allow authenticated users to select their own attempts" ON "public"."attempts" FOR SELECT USING (("player" = "auth"."uid"()));



CREATE POLICY "Allow authenticated users to update their own attempts" ON "public"."attempts" FOR UPDATE USING (("player" = "auth"."uid"())) WITH CHECK (("player" = "auth"."uid"()));



CREATE POLICY "Allow users to insert their own completed challenges" ON "public"."challenges_completed" FOR INSERT TO "authenticated" WITH CHECK (("player" = "auth"."uid"()));



ALTER TABLE "public"."attempts" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenges" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."challenges_completed" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."subscriptions" ENABLE ROW LEVEL SECURITY;




ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_challenges_completed"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_challenges_completed"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_challenges_completed"() TO "service_role";



GRANT ALL ON FUNCTION "public"."get_daily_ranking"() TO "anon";
GRANT ALL ON FUNCTION "public"."get_daily_ranking"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_daily_ranking"() TO "service_role";


















GRANT ALL ON TABLE "public"."attempts" TO "anon";
GRANT ALL ON TABLE "public"."attempts" TO "authenticated";
GRANT ALL ON TABLE "public"."attempts" TO "service_role";



GRANT ALL ON TABLE "public"."challenges" TO "anon";
GRANT ALL ON TABLE "public"."challenges" TO "authenticated";
GRANT ALL ON TABLE "public"."challenges" TO "service_role";



GRANT ALL ON TABLE "public"."challenges_completed" TO "anon";
GRANT ALL ON TABLE "public"."challenges_completed" TO "authenticated";
GRANT ALL ON TABLE "public"."challenges_completed" TO "service_role";



GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."challenges_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."subscriptions" TO "anon";
GRANT ALL ON TABLE "public"."subscriptions" TO "authenticated";
GRANT ALL ON TABLE "public"."subscriptions" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS  TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES  TO "service_role";






























RESET ALL;
